VehicleService/Controllers/CustomerController.cs
using Blueprints.DbModels;
using DbRepository;
using DbRepository.Interfaces;
using PagedList;
using System.Linq;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class CustomerController : BaseController
    {
        private ICustomerRepository _repository;

        public CustomerController()
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public CustomerController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }

        private IUnitOfWork UnitOfWork { get; set; }

        private ICustomerRepository Repository
        {
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.Customer;
                }

                return _repository;
            }
        }


        public ActionResult Autocomplete(string term)
        {
            var searchTerm = (term ?? "").Trim().ToLower();
            var model = Repository.Find(x => x.FirstName.ToLower().StartsWith(searchTerm)
                                  || x.LastName.ToLower().StartsWith(searchTerm)
                                  || x.Phone.ToLower().StartsWith(searchTerm)
                                )
                                .Take(this.EntitiesInAutocomplete)
                                .Select(x => new
                                {
                                    label = x.Name
                                });

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListAjax(string searchTerm, int pageIndex = 1)
        {
            if (Request.IsAjaxRequest())
            {
                searchTerm = (searchTerm ?? "").Trim();
                var model = Repository.Find(x => searchTerm == ""|| x.Name.StartsWith(searchTerm))
                                    .OrderBy(x => x.FirstName)
                                    .ThenBy(x => x.LastName)
                                    .ToPagedList(pageIndex, this.EntitiesPerPage);

                return PartialView("_List", model);
            }

            return HttpNotFound();
        }

        public ActionResult Index()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuCreate();
            var model = Repository.FindAll()
                               .OrderBy(x => x.FirstName)
                               .ThenBy(x => x.LastName)
                               .ToPagedList(1, this.EntitiesPerPage);
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDetails(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Create()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();

            var countries = UnitOfWork.Country.FindAllWithCities();
            ViewBag.CountryId = this.BuildSelectList(countries);

            ViewBag.CityId = Enumerable.Empty<SelectListItem>();
            return View();
        }

        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuEdit(new { id = model.Id });

                var countries = UnitOfWork.Country.FindAllWithCities();
                ViewBag.CountryId = this.BuildSelectList(countries, model.City.CountryId);

                var cities = UnitOfWork.City.FindAllByCountry(model.City.CountryId);
                ViewBag.CityId = this.BuildSelectList(cities, model.CityId);

                return View(model);
            }

            return HttpNotFound();
        }
        
        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDelete(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer model)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            ViewBag.CityId = this.BuildSelectList(UnitOfWork.City);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            ViewBag.CityId = this.BuildSelectList(UnitOfWork.City, model.CityId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                if (ModelState.IsValid)
                {
                    Repository.Remove(model);

                    var status = UnitOfWork.CommitAndGetStatus();
                    if (status.IsSuccessful)
                    {
                        return RedirectToAction(DefaultActionNames.Index);
                    }
                    else
                    {
                        //logging
                    }
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Controllers/OrderController.cs
using Blueprints.DbModels;
using DbRepository;
using DbRepository.Interfaces;
using System.Linq;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class OrderController : BaseController
    {
        private IOrderRepository _repository;


        public OrderController() 
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public OrderController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }


        private IUnitOfWork UnitOfWork { get; set; }

        private IOrderRepository Repository
        { 
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.Order;
                }

                return _repository; 
            } 
        }
        
        
        public ActionResult Index()
        {
            var model = Repository.FindAll().OrderByDescending(x => x.CreatedOn);
            return View(model);
        }

        public ActionResult Create([Bind(Prefix = "id")] int repairId)
        {
            var model = Repository.FindSingle(x => x.RepairId == repairId);
            if (model != null)
            {
                return RedirectToAction("Edit", new { id = repairId });
            }

            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
            ViewBag.RepairId = repairId;
            return View();
        }

        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                var subMenu = MenuFactory.BuildMenu();
                var repairMenuItem = MenuFactory.BuildMenuItem(
                    "Details",
                    DefaultActionNames.Details,
                    "Repair",
                    new { id = model.Repair.Id }
                );
                subMenu.Add(repairMenuItem);
                subMenu.Add(MenuFactory.MenuItemDelete(new { id = model.Id }));
                subMenu.Add(MenuFactory.MenuItemIndex());
                ViewBag.SubMenu = subMenu; 
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order model)
        {
            if (ModelState.IsValid)
            {
                var repair = UnitOfWork.Repair.FindById(model.RepairId);
                model.TotalPrice = PriceCalculator.CalculateOrderTotalPrice(model.AdditionalPrice, repair);

                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order model)
        {
            if (ModelState.IsValid)
            {
                var repair = UnitOfWork.Repair.FindById(model.RepairId);
                model.TotalPrice = PriceCalculator.CalculateOrderTotalPrice(model.AdditionalPrice, repair);

                Repository.Update(model, "IsPaid", "AdditionPrice", "TotalPrice");

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            var zmodel = Repository.FindById(model.Id);
            return View(zmodel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                Repository.Remove(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Controllers/VehicleController.cs
using Blueprints.DbModels;
using Blueprints.Models;
using DbRepository;
using DbRepository.Interfaces;
using System.Linq;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class VehicleController : BaseController
    {
        private IVehicleRepository _repository;


        public VehicleController()
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public VehicleController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }

        private IUnitOfWork UnitOfWork { get; set; }

        private IVehicleRepository Repository
        {
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.Vehicle;
                }

                return _repository;
            }
        }


        public ActionResult ListByManufacturer(int manufacturerId)
        {
            if (Request.IsAjaxRequest())
            {
                var model = Repository.FindAllByManufacturer(manufacturerId)
                                        .Select(x => new
                                        {
                                            Text = x.Name,
                                            Value = x.Id.ToString()
                                        });
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            return HttpNotFound();
        }
        public ActionResult Index()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuCreate();
            var model = Repository.FindAll().OrderBy(x => x.VehicleModel);
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDetails(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Create()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType);
            return View();
        }
        
        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuEdit(new { id = model.Id });
                ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
                ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
                return View(model);
            }

            return HttpNotFound();
        }
        
        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDelete(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle model)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vehicle model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                Repository.Remove(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Views/Shared/_DeleteConfirmationMessage.cshtml
<h3>Are you sure you want to delete this?</h3>

VehicleService/Views/Shared/_DeleteForm.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" />
    </p>
}

VehicleService/Views/Shared/_EmptyResults.cshtml
<p>No results :( </p>

VehicleService/Views/Shared/_Heading.cshtml
<h2>@ViewBag.Title</h2>

VehicleService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - АЗЛК</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")

        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">
                        @Html.ActionLink("АЗЛК", "Index", "Customer")
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_Login")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Customers", DefaultActionNames.Index, "Customer")</li>
                            <li>@Html.ActionLink("Repairs", DefaultActionNames.Index, "Repair")</li>
                            <li>@Html.ActionLink("Orders", DefaultActionNames.Index, "Order")</li>
                            <li>@Html.ActionLink("Employees", DefaultActionNames.Index, "Employee")</li>
                            <li>@Html.ActionLink("Vehicles", DefaultActionNames.Index, "Vehicle")</li>

                            @if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Admin", DefaultActionNames.Index, "Admin")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <section class="content-wrapper main-content clear-fix">
                @if (ViewBag.SubMenu != null)
                {
                     @Html.Partial("_SubMenu", (IEnumerable<IMenuItem>)ViewBag.SubMenu)
                }
                
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - АЗЛК</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/vs")
        @RenderSection("scripts", required: false)
    </body>
</html>

VehicleService/Views/Shared/_Login.cshtml
@if (Request.IsAuthenticated) {
    <text>
        Hello, @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })!
        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) 
        {
            @Html.AntiForgeryToken()
            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
        }
    </text>
} else {
    <ul>
        @*<li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>*@
        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}

VehicleService/Views/Shared/_Pager.cshtml
@model IPagedList

@if (Model.TotalItemCount > Model.PageSize)
{
    string pagerAction = DefaultActionNames.ListAjax;
    if (ViewBag.PagerAction != null)
    {
        pagerAction = ViewBag.PagerAction;
    }

    <div class="pagedList" data-vs-target="#@Constants.ItemsListId">
        @Html.PagedListPager(Model, pageIndex => Url.Action(pagerAction, new { pageIndex }), PagedListRenderOptions.Classic)
    </div>
}

VehicleService/Views/Shared/_SearchForm.cshtml
@{
    string formAction = DefaultActionNames.ListAjax;
    if (ViewBag.FormAction != null)
    {
        formAction = ViewBag.FormAction;
    }

    string autocompleteAction = DefaultActionNames.Autocomplete;
    if (ViewBag.AutocompleteAction != null)
    {
        autocompleteAction = ViewBag.AutocompleteAction;
    }
}

<div>
    <form method="get" action="@Url.Action(formAction)" data-vs-ajax="true" data-vs-target="#@Constants.ItemsListId">
        <input type="search" name="searchTerm" data-vs-autocomplete="@Url.Action(autocompleteAction)" value="" />
        <input type="submit" name="name" value="Search" />
    </form>
</div>

VehicleService/Views/Shared/_SubMenu.cshtml
@model IEnumerable<IMenuItem>

@if (Model.Any())
{
    <div class="subMenu clear-fix">
        <div class="float-right">
            <nav>
                <ul id="menu">
                    @foreach (var item in Model)
                    {
                        <li>
                            @Html.ActionLink(item.Text, item.ActionName, item.ControllerName, item.RouteValues, null)
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
}