VehicleService/Controllers/VehicleController.cs
using Blueprints.DbModels;
using Blueprints.Models;
using DbRepository;
using DbRepository.Interfaces;
using System.Linq;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class VehicleController : BaseController
    {
        private IVehicleRepository _repository;


        public VehicleController()
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public VehicleController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }

        private IUnitOfWork UnitOfWork { get; set; }

        private IVehicleRepository Repository
        {
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.Vehicle;
                }

                return _repository;
            }
        }


        public ActionResult ListByManufacturer(int manufacturerId)
        {
            if (Request.IsAjaxRequest())
            {
                var model = Repository.FindAllByManufacturer(manufacturerId)
                                        .Select(x => new
                                        {
                                            Text = x.Name,
                                            Value = x.Id.ToString()
                                        });
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            return HttpNotFound();
        }
        public ActionResult Index()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuCreate();
            var model = Repository.FindAll().OrderBy(x => x.VehicleModel);
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDetails(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Create()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType);
            return View();
        }
        
        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuEdit(new { id = model.Id });
                ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
                ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
                return View(model);
            }

            return HttpNotFound();
        }
        
        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDelete(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle model)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vehicle model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            ViewBag.VehicleManufacturerId = this.BuildSelectList(UnitOfWork.VehicleManufacturer, model.VehicleManufacturerId);
            ViewBag.VehicleTypeId = this.BuildSelectList(UnitOfWork.VehicleType, model.VehicleTypeId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                Repository.Remove(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Controllers/VehicleManufacturerController.cs
using Blueprints.DbModels;
using DbRepository;
using DbRepository.Interfaces;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class VehicleManufacturerController : BaseController
    {
        private IVehicleManufacturerRepository _repository;


        public VehicleManufacturerController()
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public VehicleManufacturerController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }

        private IUnitOfWork UnitOfWork { get; set; }

        private IVehicleManufacturerRepository Repository
        {
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.VehicleManufacturer;
                }

                return _repository;
            }
        }



        public ActionResult Index()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuCreate();
            var model = Repository.GetGroupedVehicleManufacturers();
            return View(model);
        }

        public ActionResult Details(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDetails(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Create()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
            ViewBag.CountryId = this.BuildSelectList(UnitOfWork.Country);
            return View();
        }

        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuEdit(new { id = model.Id });
                ViewBag.CountryId = this.BuildSelectList(UnitOfWork.Country, model.CountryId);

                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDelete(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleManufacturer model)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            ViewBag.CountryId = this.BuildSelectList(UnitOfWork.Country, model.CountryId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VehicleManufacturer model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            ViewBag.CountryId = this.BuildSelectList(UnitOfWork.Country, model.CountryId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                Repository.Remove(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Controllers/VehicleTypeController.cs
using Blueprints.DbModels;
using DbRepository;
using DbRepository.Interfaces;
using System.Linq;
using System.Web.Mvc;
using VehicleService.Models;
using VehicleService.Models.Factories;

namespace VehicleService.Controllers
{
    public class VehicleTypeController : BaseController
    {
        private IVehicleTypeRepository _repository;

        public VehicleTypeController()
        {
            this.UnitOfWork = UowFactory.BuildUnitOfWork();
        }

        public VehicleTypeController(IUnitOfWork unitOfWork)
        {
            this.UnitOfWork = unitOfWork;
        }

        private IUnitOfWork UnitOfWork { get; set; }

        private IVehicleTypeRepository Repository
        {
            get
            {
                if (_repository == null)
                {
                    _repository = this.UnitOfWork.VehicleType;
                }

                return _repository;
            }
        }

        public ActionResult Index()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuCreate();
            var model = Repository.FindAll().OrderBy(x => x.Name);
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.SubMenu = MenuFactory.BuildMenuIndex();
            return View();
        }

        public ActionResult Details(int id, int manufacturerId = 0)
        {
            var model = Repository.GetVehicleType(id, manufacturerId);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDetails(new { id = model.VehicleTypeId });    
                return View(model);
            }

            return HttpNotFound();
        }

        public ActionResult Edit(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuEdit(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound(); ;
        }
        
        public ActionResult Delete(int id = 0)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                ViewBag.SubMenu = MenuFactory.BuildMenuDelete(new { id = model.Id });
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VehicleType model)
        {
            if (ModelState.IsValid)
            {
                Repository.Add(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logged error ILogger TODO
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VehicleType model)
        {
            if (ModelState.IsValid)
            {
                Repository.Update(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = Repository.FindById(id);
            if (model != null)
            {
                Repository.Remove(model);

                var status = UnitOfWork.CommitAndGetStatus();
                if (status.IsSuccessful)
                {
                    return RedirectToAction(DefaultActionNames.Index);
                }
                else
                {
                    //logging
                }

                return View(model);
            }

            return HttpNotFound();
        }
    }
}

VehicleService/Views/Vehicle/Create.cshtml
@model Vehicle

@{
    ViewBag.Title = "Create";
}

@Html.Partial("_Heading")
@Html.Partial("_Form")

VehicleService/Views/Vehicle/Delete.cshtml
@model Vehicle

@{
    ViewBag.Title = "Delete";
}

@Html.Partial("_Heading")
@Html.Partial("_DeleteConfirmationMessage")
@Html.Partial("_Details")
@Html.Partial("_DeleteForm")

VehicleService/Views/Vehicle/Details.cshtml
@model Vehicle

@{
    ViewBag.Title = "Details";
}

@Html.Partial("_Heading")
@Html.Partial("_Details")

VehicleService/Views/Vehicle/Edit.cshtml
@model Vehicle

@{
    ViewBag.Title = "Edit";
}

@Html.Partial("_Heading")
@Html.Partial("_Form")

VehicleService/Views/Vehicle/Index.cshtml
@model IEnumerable<Vehicle>

@{
    ViewBag.Title = "Vehicles";
}

<h2>@ViewBag.Title: (@Model.Count())</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleManufacturer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleType.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EngineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EngineType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Transmission)
        </th>
    </tr>

    @foreach (var vehicle in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(vehicle.Name, DefaultActionNames.Details, new { id = vehicle.Id })
            </td>
            <td>
                @Html.ActionLink(vehicle.VehicleManufacturer.Name, DefaultActionNames.Details, "VehicleManufacturer", new { id = vehicle.VehicleManufacturer.Id }, null)
            </td>
            <td>
                @Html.ActionLink(vehicle.VehicleType.Name, DefaultActionNames.Details, "VehicleType", new { id = vehicle.VehicleType.Id, manufacturerId = vehicle.VehicleManufacturerId }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => vehicle.EngineName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => vehicle.EngineType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => vehicle.Transmission)
            </td>
        </tr>
    }

</table>

VehicleService/Views/Vehicle/_Details.cshtml
@model Vehicle

<div>
    <p>
        @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.VehicleModel): @Html.DisplayFor(model => model.VehicleModel)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Modifination): @Html.DisplayFor(model => model.Modifination)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Body): @Html.DisplayFor(model => model.Body)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Fuel) : @Html.DisplayFor(model => model.Fuel)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.EngineName): @Html.DisplayFor(model => model.EngineName)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.EngineType):  @Html.DisplayFor(model => model.EngineType)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Transmission):  @Html.DisplayFor(model => model.Transmission)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Year):  @Html.DisplayFor(model => model.Year)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.VehicleManufacturer.Name):  @Html.DisplayFor(model => model.VehicleManufacturer.Name)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.VehicleType.Name):  @Html.DisplayFor(model => model.VehicleType.Name)
    </p>
</div>

VehicleService/Views/Vehicle/_Form.cshtml
@model Vehicle

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if (Model != null)
    {
        @Html.HiddenFor(model => model.Id)
    }

    <fieldset>
        <legend>Vehicle</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.VehicleManufacturerId, "VehicleManufacturer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("VehicleManufacturerId")
            @Html.ValidationMessageFor(model => model.VehicleManufacturerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VehicleTypeId, "VehicleType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("VehicleTypeId")
            @Html.ValidationMessageFor(model => model.VehicleTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VehicleModel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VehicleModel)
            @Html.ValidationMessageFor(model => model.VehicleModel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Modifination)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Modifination)
            @Html.ValidationMessageFor(model => model.Modifination)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fuel)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fuel)
            @Html.ValidationMessageFor(model => model.Fuel)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EngineName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EngineName)
            @Html.ValidationMessageFor(model => model.EngineName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EngineType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EngineType)
            @Html.ValidationMessageFor(model => model.EngineType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Transmission)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Transmission)
            @Html.ValidationMessageFor(model => model.Transmission)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Year)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Year)
            @Html.ValidationMessageFor(model => model.Year)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}